[2021-08-17 15:47:35,346] (INFO) [149426409 Mixson] Msg: /getRegularStaging
[2021-08-17 15:49:22,120] (INFO) [149426409 Mixson] Msg: /getRegularStaging
[2021-08-17 15:49:26,035] (INFO) [149426409 Mixson] Msg: /getNightStagingTime
[2021-08-17 15:49:32,133] (INFO) [149426409 Mixson] Msg: /getMorningStagingTime
[2021-08-17 15:51:36,035] (INFO) [1910765771 Mixon] Msg: /getRegularStaging
[2021-08-17 16:02:06,367] (INFO) [1910765771 Mixon] Msg: /start
[2021-08-17 16:02:36,716] (INFO) [1910765771 Mixon] Msg: /start
[2021-08-17 16:02:43,012] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 229, in inner_function
    fullName = update.message.from_user.full_name
AttributeError: 'NoneType' object has no attribute 'from_user'

[2021-08-17 16:02:43,013] (ERROR) 'NoneType' object has no attribute 'from_user'
[2021-08-17 16:02:49,278] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 229, in inner_function
    fullName = update.message.from_user.full_name
AttributeError: 'NoneType' object has no attribute 'from_user'

[2021-08-17 16:02:49,278] (ERROR) 'NoneType' object has no attribute 'from_user'
[2021-08-17 16:02:56,587] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 229, in inner_function
    fullName = update.message.from_user.full_name
AttributeError: 'NoneType' object has no attribute 'from_user'

[2021-08-17 16:02:56,587] (ERROR) 'NoneType' object has no attribute 'from_user'
[2021-08-17 16:03:18,349] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 229, in inner_function
    fullName = update.message.from_user.full_name
AttributeError: 'NoneType' object has no attribute 'from_user'

[2021-08-17 16:03:18,349] (ERROR) 'NoneType' object has no attribute 'from_user'
[2021-08-17 16:03:57,312] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 229, in inner_function
    fullName = update.message.from_user.full_name
AttributeError: 'NoneType' object has no attribute 'from_user'

[2021-08-17 16:03:57,313] (ERROR) 'NoneType' object has no attribute 'from_user'
[2021-08-17 16:07:02,544] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 350, in CM_getStagingTime
    update.message.reply_text(msg, parse_mode='Markdown')
AttributeError: 'NoneType' object has no attribute 'reply_text'

[2021-08-17 16:07:02,837] (ERROR) 'NoneType' object has no attribute 'reply_text'
[2021-08-17 16:07:49,947] (ERROR) Traceback (most recent call last):
  File "D:/program/OperationalTelegram/src/telegramView.py", line 214, in inner_function
    return func(*args, **kwargs)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 350, in CM_getStagingTime
    send_message(bot, update, msg)
  File "D:/program/OperationalTelegram/src/telegramView.py", line 47, in send_message
    return bot.send_message(chat_id, text, parse_mode=ParseMode.HTML, **kwargs)
  File "<decorator-gen-118>", line 2, in send_message
  File "D:\Software\Programming_Software\Python\lib\site-packages\telegram\bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "D:\Software\Programming_Software\Python\lib\site-packages\telegram\bot.py", line 310, in send_message
    timeout=timeout, **kwargs)
  File "D:\Software\Programming_Software\Python\lib\site-packages\telegram\bot.py", line 172, in _message
    result = self._request.post(url, data, timeout=timeout)
  File "D:\Software\Programming_Software\Python\lib\site-packages\telegram\utils\request.py", line 332, in post
    body=json.dumps(data).encode('utf-8'),
  File "D:\Software\Programming_Software\Python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\Software\Programming_Software\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Software\Programming_Software\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Software\Programming_Software\Python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Update is not JSON serializable

[2021-08-17 16:07:49,947] (ERROR) Object of type Update is not JSON serializable
